### ISSUE TITLE
Determine best way to include Semantic CSS

### ISSUE THREAD

**Issue by aore** [aore/FriendMachine#7]
Work off of d9dae54 on addReact, where Webpack is removed from the process. In that commit, the CSS is linked by adding it to the html in dashboard.jsx. Can the CSS be linked without dangerouslySetInnerHtml?

**Comment by nino** [comment]
Yes, CSS can be set perfectly elegantly by e.g. adding it to a default layout (without dangerouslySetInnerHTML).

**Comment by aore** [comment]
(By this issue, I also mean "implement the best way to include Semantic." Show me!)

**Comment by aore** [comment]
Ok, I did it. I think I know what I had broken when I tried doing the same thing earlier; Stardust makes it ok.
